### ISSUE TITLE
23volts

### ISSUE THREAD

**Issue by RemiCollin** [VCVRack/community#617]
Hello, 

I'd like to add my plugin to the VCV library : 

Source : https://github.com/23volts/23volts-vcv
Commit b2398de2e3151ba852f973de10c1ebd938a743f2

Thank you !

**Comment by RemiCollin** [comment]
I was missing the .gitignore and pushing the `/build` directory, 

This is the correct commit : 858592f4dc78bd92ff2b78b285c2d0040310ffd4

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/23volts/23volts-vcv/issues/1

**Comment by cschol** [comment]
OK. There are multiple other issues:

1. Your repository contains **binaries**, e.g. `plugin.dylib` and the `dist` directory. Those should **not** be in the repository and need to be **purged** (i.e. removed from the **history** not just removed).
2. You removed the `build` directory, but the files are still present in the repository history. They need to be purged from the history also to decrease repo clone size on the build server.
3. Some files in the `res` directory are starting with a lower case letter, but referenced in the source code starting with uppercase letter. This fails on file systems that are case sensitive and panels do not show up in Rack on those platforms.

I would recommend starting with a **fresh** `git` repository to fix these issues. Cleaning history with [BFG Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) is another option, but I would think that that option is more work than starting with a fresh repository.

**Comment by RemiCollin** [comment]
Ok, I'll make a new repo and push a clean state. 

Just before I delete the current one could you point me to which file starts with a lower case in the `res/` directory ? I double-checked and couldn't find any...

Edit : nevermind, this was actually the opposite, lower case reference were in the code. Thank you for pointing it out ;)

**Comment by RemiCollin** [comment]
I created a new repo, same address.

Commit : 7faf3a135076111829b91e9495c09d2a6f7bbbfc

**Comment by cschol** [comment]
Perfect. Thank you for fixing. Looks good now and will be integrated right away.

**Comment by RemiCollin** [comment]
Question : do I need to ask for a update here at each patch version ? or is there some kind of automated process ?

**Comment by RemiCollin** [comment]
In doubt : 

Version 1.0.1 : aa580df13a044a5fb9813ce7d60d48418a9788c3

**Comment by cschol** [comment]
Yes. Please update **this** issue for every new version to trigger the review and integration. Thank you.

**Comment by RemiCollin** [comment]
1.1 release :

Commit : 04eb943602a5c35a06bb7fd8600f4c075bc70947

**Comment by cschol** [comment]
Invalid tag in `plugin.json`: https://github.com/23volts/23volts-vcv/issues/5

**Comment by RemiCollin** [comment]
Fixed on this commit : c2169262a89af9ce0ace71edddac0bb319421182

Thank you!

**Comment by RemiCollin** [comment]
Just in case, is it possible to hold off build update as v1.1.1 is nearly ready ? Thank you

**Comment by RemiCollin** [comment]
New version : 1.1.1
Commit : adffb5209b80ae3761b2b0fb54a7c04eeb9eeef2

**Comment by RemiCollin** [comment]
New version : 1.1.2
Commit : 853ab09b4cb246e4a32d07b79307cb7b8d5aebd6

**Comment by RemiCollin** [comment]
New version : 1.1.2
Commit : f8600eab712f795612322db99ce1becf3ab150e1

**Comment by RemiCollin** [comment]
@AndrewBelt : I just saw you have updated build but it show 1.1.1 instead of 1.1.2, which have a bugfix on windows (I had report 1.1.1 crashes the browser on Windows 10, which I fixed yesterday)

**Comment by Coirt** [comment]
> @AndrewBelt : I just saw you have updated build but it show 1.1.1 instead of 1.1.2, which have a bugfix on windows (I had report 1.1.1 crashes the browser on Windows 10, which I fixed yesterday)

Still crashing, the update made it to release v1.1.1
https://github.com/23volts/23volts-vcv/issues/18

**Comment by AndrewBelt** [comment]
Reverted to 1.0.1.

**Comment by RemiCollin** [comment]
Sorry for that, should have mentioned not to release the 1.1.1, just assumed you would have released the latest vetsion...

**Comment by cschol** [comment]
Which version is supposed to be released now?

**Comment by AndrewBelt** [comment]
I assume this one https://github.com/VCVRack/library/issues/617#issuecomment-573405799

**Comment by RemiCollin** [comment]
Yes that's the right one

**Comment by RemiCollin** [comment]
New version : 1.1.3
Commit : 294bcfd9b7f79eae1298d681eb9acc66745c38eb

Thank you !

**Comment by RemiCollin** [comment]
New version : 1.1.4
Commit : 10bcd5b2162824a6ff5b44d4e5010439ed87e933

Fixes glitches in Morph & Multimap

Thank you!

**Comment by RemiCollin** [comment]
Version 1.1.5
bf1f1c2cd93216b0dfd0d2483391c4a9eff2c0c7

**Comment by SteveRussell33** [comment]
This plugin is currently not in the library. I have upgraded this to v2 on my forked repo last summer - someone PM'd me on the forum asking me about this.
What would I need to do to add this to the library, presumedly asking the original owner first?

**Comment by cschol** [comment]
Yes. Get permission from the previous owner and send it to `support@vcvrack.com`. Once we have the permission, we can update the plugin to your version.
