### ISSUE TITLE
questionablemodules

### ISSUE THREAD

**Issue by isivisi** [VCVRack/community#747]
code: https://github.com/isivisi/questionablemodules
version: 2.0.1
commit: 756e96c591d383da04dec356ac0a6fc75ef203cd

modules:
- Nandomizer
- Discombobulator
- Treequencer

**Comment by isivisi** [comment]
version: 2.1.0
commit: a63d6f348abc5f06ee093d89100853a000b45b98

changes:
- Compressed images (10mb plugin file to 1mb).
- Changed treequencer screen colors to be more color blind safe.

**Comment by isivisi** [comment]
Significant repo resize with bfg
new commit: d952d8404cea280b49ec6f66e0bdd13dcb643383

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by isivisi** [comment]
version: 2.1.3
commit: 3ff67464f2871f6941202aed9e542cb5358c4ba5

changes:
- New module: SLURP
- Changed Treequencer text input to change values on input instead of on enter
- Fixed visual offset

**Comment by isivisi** [comment]
verison change: 2.1.3
<s>commit: 9abf8139108474420b943cee989adddc68d79d1f</s>
commit: 4d52e35ebeff122ecccde5d86f63003537508e6f

changes:
- New module: SLURP
- Treequencer text misalignment fix
- Treequencer input change
- Brand name change

**Comment by isivisi** [comment]
version: 2.1.4
commit: c28d31d0943c86b0b5716c775b0be6761e08a13a

- Fixed slurp being slightly out of tune

**Comment by isivisi** [comment]
version 2.1.5
commit: da8b3f064b9fcef62a1ef9c0dd436e12caa7c215

- Fixed SLURP visual inconsistency when sample rate above 44100
- Added single color theme options to all modules (light and dark)
- update documentation links for all modules

**Comment by isivisi** [comment]
version 2.1.5
updated commit: https://github.com/isivisi/questionablemodules/commit/e0d8f86e78b9a7b346ca9d7f2b288ebe62527cbc

- added global theme settings
- treequencer sequence generation
- more consistent slurp oscillation

**Comment by isivisi** [comment]
version 2.1.6
commit: https://github.com/isivisi/questionablemodules/commit/bcd7a7254def2f926a419a179c8a42bc2e39e7e7

- fixed treequencer regression introduced in 2.1.5

**Comment by isivisi** [comment]
version 2.1.7
commit: https://github.com/isivisi/questionablemodules/commit/d3a4590f3f486191454225b2de4e4279f4755844

- Fixed discombobulator and nandomizer background sizing when using solid colors.
- Report bug added to context menu
- Added "Find in Documentation" for each input and parameter in each module. (Rack 2.2.3 [required](https://github.com/VCVRack/Rack/blob/v2/CHANGELOG.md?plain=1#L7) for port context to change)
- Code cleanup
- Descriptors for params
- SLURP select projection plane

**Comment by isivisi** [comment]
version 2.1.8
commit: https://github.com/isivisi/questionablemodules/commit/7f6fd055a4e1cd1d4ccb7b408637166c428530c5
- SLURP Oscillator now has a stereo option.
- SLURP also has a new polyphonic mode called spread.
- Can now disable SLURPs octave knob quantization for more fine tune offsets.
- Rack 2.4.0 prefer dark panel is taken into account for newly created modules.

**Comment by isivisi** [comment]
sorry, found some small things to add:
version 2.1.8a
commit: https://github.com/isivisi/questionablemodules/commit/2e227e45220fa103e1619672dcf2fcc74b9f12ca
- fixed typo
- fixed abnormal artifacts in visuals when using spread

**Comment by AndrewBelt** [comment]
I've updated this, but since `2.1.8a < 2.1.8` in `rack::string::Version`, this won't trigger an update. Increment the revision number to release an update.

**Comment by isivisi** [comment]
version: 2.1.9
commit: https://github.com/isivisi/questionablemodules/commit/e845946b079828f614cae40de704365a6c596447
- option to set SLURP to half rate processing (wip)
- fixed 'set quantize' option in SLURP not changing the knobs snap mode
- fixed chance offset in treequencer being set with snap enabled
- added indicators to show selected options in context menus
- fixed discombobulator descriptors being swapped
- added visuals to discombobulator

**Comment by isivisi** [comment]
version: 2.1.10
commit: https://github.com/isivisi/questionablemodules/commit/ebf621b96c53644e5b4ad1707171ec25993147fe
- Greenscreen module
- Night-bin module
- normalizeSpreadVolume is now properly saved in SLURP

**Comment by AndrewBelt** [comment]
These look like the following on Linux.

![2023-09-12T23:52:56-04:00](https://github.com/VCVRack/library/assets/338179/a82bfa29-eb3d-4ed1-92ec-6c8b984361e1)

**Comment by isivisi** [comment]
Was probably my logic for preferDarkPanels not doing anything when it gets disabled, leaving your set theme to dark for the whole questionable modules plugin. It should now just set it back to the default theme. I also fixed the missing text for nandomizer and discombolulator in dark mode.

the new commit is here: https://github.com/isivisi/questionablemodules/commit/350ce860ae9fd56b92394fffd71134cec99b165e .

**Comment by cschol** [comment]
The labels still don't show up when inserting the module (on Ubuntu):

![image](https://github.com/VCVRack/library/assets/624427/4d43da99-9091-49e3-8758-8ac31831c8dd)

**Comment by isivisi** [comment]
Oh, I see so its not the dark panel stuff, 

that has been the default since the modules came out. The labels were a later addition and disabled by default. 2.1.10 changed their initial state to enabled but that wont change the setting for people already using the plugin, only new installs moving forward. they can be toggled in the context menu.

This is expected behavior :)

**Comment by cschol** [comment]
Aha! Got it. :)

**Comment by isivisi** [comment]
new version: 2.1.11
commit: https://github.com/isivisi/questionablemodules/commit/47c0ba5f90440620dabbf1580b9a89e10be44f33
- nightbin plugin list sorted, separated by selected / not selected, limited to github sourceUrl for now
- nightbin option to add all plugins
- <b>fixed nightbin arm64 crash on exit (modulebrowser widget destructor)</b>
- Greenscreen fixed showText logic being overridden by module background color change logic
- Treequencer now zooms towards mouse position
- Treequencer note representation (squares, note letter, number) options. defaults to number
- Treequencer follow node option
- treequencer node chance is now set with a slider
- Fixed rare Treequencer crash when toggling trigger type with bounce enabled
- greenscreen added option for custom rgb, can be saved globally
- greenscreen font color auto changes based on contrast with bg color

**Comment by isivisi** [comment]
version: 2.1.12
commit: https://github.com/isivisi/questionablemodules/commit/8d5427e5cec9447838babddf0a1c196f2f0f6960

- Smute module
- Sequence Generation updates
- Treequencer history undo / redo buttons
- Treequencer follow button
- Greenscreen CV Inputs for rgb channels
- Greenscreen toggleable rail visuals
- Greenscreen toggleable shadow
- Discombobulator and Nandomizer now support polyphonic inputs
- Knob visual changes

**Comment by isivisi** [comment]
version: 2.1.13
commit: https://github.com/isivisi/questionablemodules/commit/90e1d576b90f4bc88367b3dfdac24eb08bd3970e
- Light Opacity, Random Ratio, and Soft/Hard Transition options for Smute
- Internal clocks for Smute and Treequencer now wait 1ms before triggering after a reset. In accordance with VCV [timing standards](https://vcvrack.com/manual/VoltageStandards#Timing)
- [Smute Expander](https://isivisi.github.io/questionablemodules/smute#Expanders) logic no longer locks you out of pressing Smute buttons down the chain.
- Greenscreen box shadow can now have a customizable color.

**Comment by isivisi** [comment]
verison: 2.1.14
commit: https://github.com/isivisi/questionablemodules/commit/75e5f709197de54fcc51e8b6df2facc5ced767c6
- New dephase option for SLURP
- Bad json in questionablemodules.json now regenerates settings instead of just crashing
